import { PanelComponentDef } from '../../shared/types/index.ts';

export const COMPONENT_CATALOG: PanelComponentDef[] = [
  {
    id: 'comp-mccb-nsx100',
    name: 'MCCB 3P 100A',
    category: 'POWER',
    manufacturer: 'Schneider Electric',
    model: 'Compact NSX100F',
    description: '3-pole Molded Case Circuit Breaker 100A 36kA',
    width: 105,
    height: 161,
    depth: 86,
    mountingType: 'MOUNTING_PLATE',
    clearance: { top: 60, bottom: 60, left: 25, right: 25, front: 50 },
    color: '#343a40',
    terminalsTop: 3,
    terminalsBottom: 3
  },
  {
    id: 'comp-mcb-3p-32a',
    name: 'MCB 3P 32A C-Curve',
    category: 'POWER',
    manufacturer: 'Schneider Electric',
    model: 'Acti9 iC60N 3P 32A',
    description: 'Miniature Circuit Breaker 3-Pole 32A',
    width: 54,
    height: 85,
    depth: 78,
    mountingType: 'DIN_RAIL',
    clearance: { top: 30, bottom: 30, left: 5, right: 5, front: 20 },
    color: '#495057',
    terminalsTop: 3,
    terminalsBottom: 3
  },
  {
    id: 'comp-mcb-1p-10a',
    name: 'MCB 1P 10A C-Curve',
    category: 'POWER',
    manufacturer: 'Schneider Electric',
    model: 'Acti9 iC60N 1P 10A',
    description: 'Miniature Circuit Breaker 1-Pole 10A',
    width: 18,
    height: 85,
    depth: 78,
    mountingType: 'DIN_RAIL',
    clearance: { top: 25, bottom: 25, left: 2, right: 2, front: 20 },
    color: '#495057',
    terminalsTop: 1,
    terminalsBottom: 1
  },
  {
    id: 'comp-vfd-atv320-075',
    name: 'VFD 0.75kW 3P 380V',
    category: 'DRIVE',
    manufacturer: 'Schneider Electric',
    model: 'Altivar Machine ATV320U07N4B',
    description: 'Variable Speed Drive 0.75kW 3-Phase 380-500V',
    width: 72,
    height: 143,
    depth: 138,
    mountingType: 'DIN_RAIL',
    clearance: { top: 100, bottom: 100, left: 20, right: 20, front: 40 },
    color: '#1c7ed6',
    terminalsTop: 3,
    terminalsBottom: 4
  },
  {
    id: 'comp-vfd-atv320-22',
    name: 'VFD 2.2kW 3P 380V',
    category: 'DRIVE',
    manufacturer: 'Schneider Electric',
    model: 'Altivar Machine ATV320U22N4B',
    description: 'Variable Speed Drive 2.2kW 3-Phase 380-500V',
    width: 105,
    height: 184,
    depth: 158,
    mountingType: 'DIN_RAIL',
    clearance: { top: 100, bottom: 100, left: 20, right: 20, front: 50 },
    color: '#1864ab',
    terminalsTop: 3,
    terminalsBottom: 4
  },
  {
    id: 'comp-plc-tm221',
    name: 'PLC Controller 24 I/O',
    category: 'IO',
    manufacturer: 'Schneider Electric',
    model: 'Modicon M221 TM221CE24T',
    description: 'Logic Controller 24 I/O Transistor Source Ethernet',
    width: 110,
    height: 90,
    depth: 70,
    mountingType: 'DIN_RAIL',
    clearance: { top: 40, bottom: 40, left: 20, right: 20, front: 30 },
    color: '#2b8a3e',
    terminalsTop: 8,
    terminalsBottom: 8
  },
  {
    id: 'comp-psu-24v-5a',
    name: 'Power Supply 24VDC 5A',
    category: 'CONTROL',
    manufacturer: 'Mean Well',
    model: 'NDR-120-24',
    description: '120W Single Output Industrial DIN Rail Power Supply',
    width: 40,
    height: 125,
    depth: 113,
    mountingType: 'DIN_RAIL',
    clearance: { top: 40, bottom: 20, left: 10, right: 10, front: 30 },
    color: '#e67700',
    terminalsTop: 3,
    terminalsBottom: 4
  },
  {
    id: 'comp-contactor-lc1d09',
    name: 'Contactor 9A 220VAC',
    category: 'CONTROL',
    manufacturer: 'Schneider Electric',
    model: 'TeSys D LC1D09M7',
    description: '3-pole Contactor 9A 4kW@400V Coil 220VAC',
    width: 45,
    height: 77,
    depth: 86,
    mountingType: 'DIN_RAIL',
    clearance: { top: 30, bottom: 30, left: 5, right: 5, front: 25 },
    color: '#5c7cfa',
    terminalsTop: 4,
    terminalsBottom: 4
  },
  {
    id: 'comp-relay-module-4p',
    name: 'Slim Relay Module 4-Ch',
    category: 'CONTROL',
    manufacturer: 'Finder',
    model: '39 Series MasterPLUS',
    description: 'Interface Relay 24VDC 6A SPDT 4-gang assembly',
    width: 25,
    height: 90,
    depth: 75,
    mountingType: 'DIN_RAIL',
    clearance: { top: 20, bottom: 20, left: 5, right: 5, front: 15 },
    color: '#0ca678',
    terminalsTop: 4,
    terminalsBottom: 4
  },
  {
    id: 'comp-terminals-group',
    name: 'Terminal Blocks Group (10x)',
    category: 'STRUCTURE',
    manufacturer: 'Phoenix Contact',
    model: 'UT 2,5 Group',
    description: 'Feed-through terminal block 2.5mm² 10 pieces gang',
    width: 52,
    height: 47,
    depth: 47,
    mountingType: 'DIN_RAIL',
    clearance: { top: 30, bottom: 30, left: 5, right: 5, front: 10 },
    color: '#868e96',
    terminalsTop: 10,
    terminalsBottom: 10
  },
  {
    id: 'comp-vfd-15kw',
    name: 'Heavy VFD 15kW (Deep)',
    category: 'DRIVE',
    manufacturer: 'Schneider Electric',
    model: 'Altivar Machine ATV320D15N4B',
    description: 'Variable Speed Drive 15kW (Requires 270mm usable depth with front clearance)',
    width: 180,
    height: 330,
    depth: 210,
    mountingType: 'MOUNTING_PLATE',
    clearance: { top: 150, bottom: 150, left: 30, right: 30, front: 60 },
    color: '#092b60',
    terminalsTop: 3,
    terminalsBottom: 4
  }
];

